# GirlTHing AI Lab — Radionica 1
## NumPy, Pandas i osnove linearne algebre

Ovaj notebook je uvod u tri alata/koncepta koje ćemo koristiti tokom cijelog ML/Data Science bloka:

1. **NumPy** — rad s nizovima brojeva (osnova za skoro sve u ML-u)
2. **Linearna algebra** — brzi podsjetnik (vektori, matrice) — vjerovatno vam je poznato, samo vidimo kako se to radi u kodu
3. **Pandas** — rad s tabelarnim podacima (DataFrame) — ovo ćemo najviše koristiti


---

# Dio 1 — NumPy

Plan:

* Kreiranje nizova (arrays)
* Osnovna svojstva niza: `shape`, `ndim`, `dtype`
* Indeksiranje i slicing
* Višedimenzionalni nizovi
* Nasumično generisani nizovi
* Operacije element-po-element
    * Operacije poređenja
    * Logičke operacije i filtriranje
* Sumarizacione operacije i `axis`

In [280]:
import numpy as np

In [281]:
np

## Kreiranje nizova

In [282]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [283]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [284]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [285]:
import numpy as np

a = np.array([1, 2, 3, 5, 7, 12])
a

array([ 1,  2,  3,  5,  7, 12])

### Prvo pogledajmo kakav niz imamo

Prije obrade podataka često želimo znati:

* koliko elemenata/dimenzija imamo,
* kakav je oblik niza,
* kojeg su tipa vrijednosti.

In [286]:
a.shape

(6,)

In [287]:
a.ndim

1

In [288]:
a.dtype

dtype('int64')

In [289]:
len(a)

6

In [290]:
a[2] = 10

In [291]:
a

array([ 1,  2, 10,  5,  7, 12])

### Šta ako pokušamo upisati element na poziciju koja ne postoji?

NumPy niz ima definisanu veličinu/oblik. Možemo mijenjati postojeće elemente, ali ne možemo samo dodijeliti vrijednost novom indeksu.

In [292]:
try:
    a[6] = 13
except IndexError as error:
    print(f"{type(error).__name__}: {error}")

IndexError: index 6 is out of bounds for axis 0 with size 6

Ako nam zaista treba novi element, možemo napraviti novi niz pomoću `np.append()`:

In [293]:
a = np.append(a, 13)
a

array([ 1,  2, 10,  5,  7, 12, 13])

### Indeksiranje i slicing

U Data Science-u često ne želimo samo jedan element nego dio niza.

In [294]:
a[0]      # prvi element

np.int64(1)

In [295]:
a[1:4]    # indeksi 1, 2 i 3

array([ 2, 10,  5])

In [296]:
a[:3]     # prva tri elementa

array([ 1,  2, 10])

In [297]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [298]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

`arange` zadaje **korak**, dok `linspace` zadaje **koliko ravnomjerno raspoređenih tačaka želimo** između početne i krajnje vrijednosti.

<h3 style="color:red">ZADATAK BR. 1</h3>

- Kreiraj niz [5, 10, 15, 20, 25]. 
- Ispiši treći element. 
- Promijeni drugi element u 100.
- Iz istog niza izdvoji prva 3 elementa i zatim elemente od indeksa 1 do 3.

In [299]:
# Probaj sama:
import numpy as np

In [300]:
a=np.array([5,10,15,20,25])

In [301]:
a[2]

np.int64(15)

In [302]:
a[1]=100

In [303]:
b=a[:3]

In [304]:
b

array([  5, 100,  15])

In [305]:
c=a[1:3]

In [306]:
c

array([100,  15])

## Višedimenzionalni nizovi

In [307]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [308]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [309]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [310]:
n.shape

(3, 3)

In [311]:
n.ndim

2

Kod 2D niza prvi indeks označava **red**, a drugi **kolonu**.

In [312]:
n[0, :]   # prvi red

array([1, 2, 3])

In [313]:
n[:, 0]   # prva kolona

array([1, 4, 7])

In [314]:
n[0, 1] = 20

In [315]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [316]:
n[2] = [1, 1, 1]

In [317]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [318]:
n[:, 2] = [0, 1, 2]

In [319]:
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

<h3 style="color:red">ZADATAK BR. 2</h3>

- Napravi matricu [[10,20,30],[40,50,60],[70,80,90]]. Izdvoji drugi red i treću kolonu.

In [320]:
# Probaj sama:
import numpy as np
n=np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
n[1,:]
n[:,2]

array([30, 60, 90])

## Nasumično generisani nizovi

In [321]:
np.random.seed(2)
100 * np.random.rand(5, 2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [322]:
np.random.seed(2)
np.random.randn(5, 2)
np.random.randn(5, 2)

array([[ 0.55145404,  2.29220801],
       [ 0.04153939, -1.11792545],
       [ 0.53905832, -0.5961597 ],
       [-0.0191305 ,  1.17500122],
       [-0.74787095,  0.00902525]])

In [323]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

## Operacije element-po-element

In [324]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [325]:
b = (10 + (a * 2)) ** 2 / 100

In [326]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [327]:
a / b + 10

array([10.        , 10.69444444, 11.02040816, 11.171875  , 11.2345679 ])

## Operacije poređenja

In [328]:
a

array([0, 1, 2, 3, 4])

In [329]:
a >= 2

array([False, False,  True,  True,  True])

In [330]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [331]:
a > b

array([False, False,  True,  True,  True])

Više uslova možemo kombinovati sa `&` (**I**) i `|` (**ILI**). Svaki uslov stavljamo u zagrade:

In [332]:
(a >= 1) & (a <= 3)

array([False,  True,  True,  True, False])

In [333]:
a[(a >= 1) & (a <= 3)]

array([1, 2, 3])

Logičko indeksiranje — izdvoji samo elemente koji zadovoljavaju uslov:

In [334]:
a[a > b]

array([2, 3, 4])

<h3 style="color:red">ZADATAK BR. 3</h3>

- Za a = np.array([1,2,3,4,5]) napravi novi niz gdje je svaki element pomnožen sa 10.

In [335]:
# Probaj sama:
a=np.array([1,2,3,4,5])
b=a*10
b

array([10, 20, 30, 40, 50])

<h3 style="color:red">ZADATAK BR. 4</h3>

- Iz a = np.array([3,7,2,9,12,4]) izdvoji samo vrijednosti veće od 5. Dodatni zadatak izdvoji vrijednosti između 5 i 10.

In [336]:
# Probaj sama:
a=np.array([1,2,3,4,5,6,7,8,11,12])
c=a[(a>5)]
b=a[(a>5)& (a<10)]
b
c

array([ 6,  7,  8, 11, 12])

## Sumarizacione operacije

Najčešće sumarizacione operacije daju jednu vrijednost koja opisuje cijeli niz:

In [337]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8, 11, 12])

In [338]:
a.sum()

np.int64(59)

In [339]:
a.mean()

np.float64(5.9)

In [340]:
a.min()

np.int64(1)

In [341]:
a.max()

np.int64(12)

In [342]:
a.std()   # standardna devijacija

np.float64(3.477067730142742)

Kod matrica možemo birati po kojoj osi računamo rezultat.

In [343]:
m = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
m

array([[10, 20, 30],
       [40, 50, 60]])

In [344]:
m.mean(axis=0)   # prosjek po kolonama

array([25., 35., 45.])

In [345]:
m.mean(axis=1)   # prosjek po redovima

array([20., 50.])

<h3 style="color:red">ZADATAK BR. 5</h3>

- Izračunaj min, max, mean i sum za niz [12,15,18,20,25].

In [346]:
# Probaj sama:
a=np.array([12,15,18,20,25])
a.min()
a.max()
a.mean(axis=0)
a.sum()

np.int64(90)

# Dio 2 — Linearna algebra (brzi podsjetnik)

_Ovo vam je vjerovatno poznato od prije — cilj je vidjeti kako se vektorske i matrične operacije rade u NumPy-u, jer se koriste kod skoro svakog ML modela._

Plan:

* Operacije nad vektorima
* Množenje
    * Množenje vektor–vektor
    * Množenje matrica–vektor
    * Množenje matrica–matrica
* Operator `@` za matrično množenje
* Transponovanje matrice
* Jedinična matrica (identity)
* Inverzna matrica

## Operacije nad vektorima

In [347]:
u = np.array([2, 4, 5, 6])

In [348]:
2 * u

array([ 4,  8, 10, 12])

In [349]:
v = np.array([1, 0, 0, 2])

In [350]:
u + v

array([3, 4, 5, 8])

In [351]:
u * v

array([ 2,  0,  0, 12])

## Množenje

In [352]:
v.shape[0]

4

**Vektor · vektor** (skalarni proizvod) — napišimo ga prvo ručno, da se vidi šta se dešava:

In [353]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
    
    return result

In [354]:
vector_vector_multiplication(u, v)

np.float64(14.0)

NumPy ovo već ima ugrađeno (i puno brže):

In [355]:
u.dot(v)

np.int64(14)

In [356]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1],
])

In [357]:
U.shape

(3, 4)

**Matrica · vektor** — svaki red matrice pomnožimo (skalarno) sa vektorom:

In [358]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    
    return result

In [359]:
matrix_vector_multiplication(U, v)

array([14.,  5.,  5.])

In [360]:
U.dot(v)

array([14,  5,  5])

In [361]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1], 
    [0, 2, 1],
    [2, 1, 0],
])

**Matrica · matrica** — kombinacija prethodnog, kolonu po kolonu:

In [362]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result

In [363]:
matrix_matrix_multiplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [364]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

### Operator `@`

U modernom Python/NumPy kodu operator `@` vrlo jasno označava matrično množenje:

In [365]:
u @ v

np.int64(14)

In [366]:
U @ v

array([14,  5,  5])

In [367]:
U @ V

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

### Transponovanje matrice

Transponovanje zamijeni redove i kolone:

In [368]:
U.T

array([[2, 1, 3],
       [4, 2, 1],
       [5, 1, 2],
       [6, 2, 1]])

## Jedinična matrica (identity)

Množenje bilo čega jediničnom matricom vraća isti rezultat (kao množenje brojem 1):

In [369]:
I = np.eye(3)

In [370]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [371]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

## Inverzna matrica

In [372]:
Vs = V[[0, 1, 2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [373]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

Matrica pomnožena svojom inverznom matricom daje jediničnu matricu:

In [374]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Dio 3 — Pandas

Plan:

* DataFrame-ovi
* Kako podatke učitavamo iz CSV fajla
* Brza inspekcija podataka: `shape`, `columns`, `dtypes`, `info()`
* Series
* Indeks: `loc` i `iloc`
* Pristupanje elementima
* Operacije element-po-element
* Filtriranje
* Operacije nad tekstom (stringovima)
* Sumarizacione operacije
* Kategorijske vrijednosti: `value_counts()`
* Nedostajuće vrijednosti
* Grupisanje
* Dobijanje NumPy nizova iz DataFrame-a

In [375]:
import numpy as np
import pandas as pd

## DataFrame-ovi

DataFrame možemo napraviti od liste listi + posebne liste naziva kolona:

In [376]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [377]:
df = pd.DataFrame(data, columns=columns)

In [378]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

Ili — često praktičnije — od liste rječnika (dict), gdje su ključevi nazivi kolona:

In [379]:
data = [
    {
        "Make": "Nissan",
        "Model": "Stanza",
        "Year": 1991,
        "Engine HP": 138.0,
        "Engine Cylinders": 4,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "sedan",
        "MSRP": 2000
    },
    {
        "Make": "Hyundai",
        "Model": "Sonata",
        "Year": 2017,
        "Engine HP": None,
        "Engine Cylinders": 4,
        "Transmission Type": "AUTOMATIC",
        "Vehicle_Style": "Sedan",
        "MSRP": 27150
    },
    {
        "Make": "Lotus",
        "Model": "Elise",
        "Year": 2010,
        "Engine HP": 218.0,
        "Engine Cylinders": 4,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "convertible",
        "MSRP": 54990
    },
    {
        "Make": "GMC",
        "Model": "Acadia",
        "Year": 2017,
        "Engine HP": 194.0,
        "Engine Cylinders": 4,
        "Transmission Type": "AUTOMATIC",
        "Vehicle_Style": "4dr SUV",
        "MSRP": 34450
    },
    {
        "Make": "Nissan",
        "Model": "Frontier",
        "Year": 2017,
        "Engine HP": 261.0,
        "Engine Cylinders": 6,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "Pickup",
        "MSRP": 32340
    }
]

In [380]:
df = pd.DataFrame(data)
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

### Kako podaci obično ulaze u Pandas

U praksi DataFrame najčešće nećemo ručno unositi. Podatke ćemo učitavati iz CSV/Excel fajlova, baza ili API-ja.

Najčešći primjer za CSV je:

In [381]:
# Primjer za stvarni fajl:
# df = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv")

### Prva inspekcija nepoznatog skupa podataka

Kada dobijemo novi dataset, prije analize želimo brzo saznati njegovu veličinu, kolone, tipove podataka i nedostajuće vrijednosti.

In [382]:
print("Shape:", df.shape)
print("Columns:", df.columns.tolist())

Shape: (5, 8)
Columns: ['Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders', 'Transmission Type', 'Vehicle_Style', 'MSRP']

In [383]:
df.dtypes

Make                     str
Model                    str
Year                   int64
Engine HP            float64
Engine Cylinders       int64
Transmission Type        str
Vehicle_Style            str
MSRP                   int64
dtype: object

In [384]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Make               5 non-null      str
 1   Model              5 non-null      str
 2   Year               5 non-null      int64
 3   Engine HP          4 non-null      float64
 4   Engine Cylinders   5 non-null      int64
 5   Transmission Type  5 non-null      str
 6   Vehicle_Style      5 non-null      str
 7   MSRP               5 non-null      int64
dtypes: float64(1), int64(3), str(4)
memory usage: 452.0 bytes

`head(n)` prikazuje samo prvih n redova — korisno kad je tabela velika:

In [385]:
df.head(n=2)

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150

## Series

Jedna kolona DataFrame-a zove se **Series**. Postoje dva načina da je izdvojimo:

Pažnja — ovo neće raditi jer naziv kolone sadrži razmak (`Engine HP`), pa Python ne zna gdje prestaje naziv atributa:

In [386]:
try:
    compile("df.Engine HP", "<example>", "eval")
except SyntaxError as error:
    print(f"{type(error).__name__}: {error.msg}")

SyntaxError: invalid syntax

Zato uvijek koristimo pristup preko srednjih zagrada — radi za bilo koji naziv kolone:

In [387]:
df['Engine HP']

0    138.0
1      NaN
2    218.0
3    194.0
4    261.0
Name: Engine HP, dtype: float64

Više kolona odjednom — proslijedimo listu naziva:

In [388]:
df[['Make', 'Model', 'MSRP']]

      Make     Model   MSRP
0   Nissan    Stanza   2000
1  Hyundai    Sonata  27150
2    Lotus     Elise  54990
3      GMC    Acadia  34450
4   Nissan  Frontier  32340

Dodavanje nove kolone je jednostavno — samo joj dodijelimo listu vrijednosti:

In [389]:
df['id'] = [1, 2, 3, 4, 5]

In [390]:
df['id'] = [10, 20, 30, 40, 50]

In [391]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,10
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,20
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,30
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,40
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,50

Brisanje kolone:

In [392]:
del df['id']

In [393]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

## Indeks

Svaki DataFrame ima indeks — oznaku za svaki red (podrazumijevano su to brojevi 0, 1, 2...):

In [394]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [395]:
df.Make.index

RangeIndex(start=0, stop=5, step=1)

Indeks možemo i sami postaviti:

In [396]:
df.index = ['a', 'b', 'c', 'd', 'e']

In [397]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
a,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
d,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
e,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

`iloc` bira redove po **poziciji**, bez obzira na indeks:

In [398]:
df.iloc[[1, 2, 4]]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
e,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

`loc` bira redove prema **oznaci indeksa**, dok `iloc` bira prema **poziciji**:

In [399]:
df.loc[['b', 'c', 'e']]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
e,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

Vraćanje na podrazumijevani numerički indeks:

In [400]:
df = df.reset_index(drop=True)

In [401]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

## Operacije element-po-element

Isto kao kod NumPy nizova — operacija se primjenjuje na svaki element odjednom:

In [402]:
df['Engine HP'] * 2

0    276.0
1      NaN
2    436.0
3    388.0
4    522.0
Name: Engine HP, dtype: float64

In [403]:
df['Year'] >= 2015

0    False
1     True
2    False
3     True
4     True
Name: Year, dtype: bool

## Filtriranje

Uslov (npr. `df['Year'] >= 2015`) vraća niz True/False vrijednosti — koristimo ga da izdvojimo samo redove koji zadovoljavaju uslov:

In [404]:
df[
    df['Make'] == 'Nissan'
]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

Više uslova kombinujemo sa `&` (I) ili `|` (ILI) — svaki uslov mora biti u zagradama:

In [405]:
df[
    (df['Make'] == 'Nissan') & (df['Year'] >= 2015)
]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

## Operacije nad tekstom (stringovima)

Čisti Python string ima svoje metode:

In [406]:
'AI Lab Radionica 1'.replace(' ', '_')

'AI_Lab_Radionica_1'

Pandas ima iste metode, ali preko `.str`, pa se primjenjuju na cijelu kolonu odjednom:

In [407]:
df['Vehicle_Style'].str.lower()

0          sedan
1          sedan
2    convertible
3        4dr suv
4         pickup
Name: Vehicle_Style, dtype: str

Metode se mogu ulančati (chain) — ovo mijenja kolonu trajno:

In [408]:
df['Vehicle_Style'] = df['Vehicle_Style'].str.replace(' ', '_').str.lower()

In [409]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr_suv,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,pickup,32340

## Sumarizacione operacije

`describe()` daje brzi statistički pregled svih brojčanih kolona

In [410]:
df.describe().round(2)

          Year  Engine HP  Engine Cylinders      MSRP
count     5.00       4.00              5.00      5.00
mean   2010.40     202.75              4.40  30186.00
std      11.26      51.30              0.89  18985.04
min    1991.00     138.00              4.00   2000.00
25%    2010.00     180.00              4.00  27150.00
50%    2017.00     206.00              4.00  32340.00
75%    2017.00     228.75              4.00  34450.00
max    2017.00     261.00              6.00  54990.00

Koliko različitih (unikatnih) vrijednosti ima svaka kolona:

In [411]:
df.nunique()

Make                 4
Model                5
Year                 3
Engine HP            4
Engine Cylinders     2
Transmission Type    2
Vehicle_Style        4
MSRP                 5
dtype: int64

Za kategorijske kolone često želimo vidjeti **koje vrijednosti postoje i koliko puta se pojavljuju**:

In [412]:
df['Transmission Type'].value_counts()

Transmission Type
MANUAL       3
AUTOMATIC    2
Name: count, dtype: int64

## Nedostajuće vrijednosti

Broj nedostajućih (NaN) vrijednosti po koloni

In [413]:
df.isnull().sum()

Make                 0
Model                0
Year                 0
Engine HP            1
Engine Cylinders     0
Transmission Type    0
Vehicle_Style        0
MSRP                 0
dtype: int64

Samo otkriti nedostajuće vrijednosti nije dovoljno — moramo odlučiti šta s njima.

Jedna mogućnost je zamijeniti ih nulom:

In [414]:
df['Engine HP'].fillna(0)

0    138.0
1      0.0
2    218.0
3    194.0
4    261.0
Name: Engine HP, dtype: float64

Druga mogućnost je, zavisno od problema, zamijeniti ih npr. prosječnom vrijednošću:

In [415]:
df['Engine HP'].fillna(df['Engine HP'].mean())

0    138.00
1    202.75
2    218.00
3    194.00
4    261.00
Name: Engine HP, dtype: float64

## Grupisanje

Ako znate SQL, ovo vam je poznato — `groupby` u pandasu odgovara `GROUP BY` u SQL-u:

```
SELECT 
    transmission_type,
    AVG(MSRP)
FROM
    cars
GROUP BY
    transmission_type
```

U pandasu:

In [416]:
df.groupby('Transmission Type')['MSRP'].mean()

Transmission Type
AUTOMATIC    30800.000000
MANUAL       29776.666667
Name: MSRP, dtype: float64

<h3 style="color:red">ZADATAK BR. 6</h3>

Koristeći `df`:

1. pronađi sve Nissan automobile
2. pronađi samo automobile sa `MANUAL` mjenjačem,
3. izračunaj prosječnu cijenu (`MSRP`) po godini proizvodnje.

In [417]:
df.groupby('Year')['MSRP'].mean().sort_index()

Year
1991     2000.000000
2010    54990.000000
2017    31313.333333
Name: MSRP, dtype: float64

In [418]:
# Probaj sama:
df[
    df['Transmission Type'] == 'MANUAL'
]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
4,Nissan,Frontier,2017,261.0,6,MANUAL,pickup,32340

In [419]:
df[
    df['Make'] == 'Lotus'
]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990

## Dobijanje NumPy nizova iz DataFrame-a

Kad god zatreba, iz Series-a ili DataFrame-a možemo izvući "čisti" NumPy niz pomoću `to_numpy()`:

In [420]:
df['MSRP'].to_numpy()

array([ 2000, 27150, 54990, 34450, 32340])

Ili cijeli DataFrame kao listu rječnika (npr. za slanje kroz API, JSON, itd.):

In [421]:
df.to_dict(orient='records')

[{'Make': 'Nissan',
  'Model': 'Stanza',
  'Year': 1991,
  'Engine HP': 138.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'sedan',
  'MSRP': 2000},
 {'Make': 'Hyundai',
  'Model': 'Sonata',
  'Year': 2017,
  'Engine HP': nan,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': 'sedan',
  'MSRP': 27150},
 {'Make': 'Lotus',
  'Model': 'Elise',
  'Year': 2010,
  'Engine HP': 218.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'convertible',
  'MSRP': 54990},
 {'Make': 'GMC',
  'Model': 'Acadia',
  'Year': 2017,
  'Engine HP': 194.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': '4dr_suv',
  'MSRP': 34450},
 {'Make': 'Nissan',
  'Model': 'Frontier',
  'Year': 2017,
  'Engine HP': 261.0,
  'Engine Cylinders': 6,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'pickup',
  'MSRP': 32340}]

---

## Kraj — šta dalje

Ovo pokriva osnove NumPy-a i Pandasa koje ćemo koristiti tokom cijelog ML/Data Science bloka.

Važna veza koju ćemo stalno koristiti:

**Pandas DataFrame → čišćenje i izbor feature-a → NumPy nizovi/matrice → ML model**

Ne morate pamtiti svaku funkciju. Važnije je da prepoznate obrazac rada: **učitaj → pregledaj → očisti → filtriraj → transformiši → analiziraj/modeliraj**.